### ISSUE TITLE
Update building data in production database

### ISSUE THREAD

**Issue by tabeckers** [Laixer/FunderMaps#175] opened 2020-07-30 08:55 UTC
Our development premise (now geocoder.building) table is more complete than the production premise table. This "new" data should be appended to the production database for a more complete product.

**Comment by tabeckers** [comment] 2020-07-30 16:19
The following tables have been updated:

- [ ] City
- [ ] Designation
- [ ] Residential Object
- [ ] Premise

**Comment by tabeckers** [comment] 2020-07-30 16:20
The premise table contains POLYGON geometries. These should be MULTIPOLYGON geometries, as stored in the BAG and as exported by the LVBAG GDAL driver. Converting these POLYGON geometries might be more complicated than a simple replacement query, since it could bring extra bugs to the table.

**Comment by tabeckers** [comment] 2020-07-31 09:12
The premise table was appended with the result of st_dump as geom. This function returns the first POLYGON in a MULTIPOLYGON when a MULTIPOLYGON is the input argument. No upsert was performed, since we can't guarantee that this first POLYGON is correct.

**Comment by yorickdewid** [comment] 2020-07-31 09:32
Waiting on confirmation from @DonZandbergen

**Comment by tabeckers** [comment] 2020-08-04 09:11
Foreign keys from address to building should be updated.

**Comment by DonZandbergen** [comment] 2020-08-04 09:12
Test (Schiedam):

![image](https://user-images.githubusercontent.com/46600362/89275972-4f4fbc80-d643-11ea-9d1c-82696f5e5a64.png)

**Comment by yorickdewid** [comment] 2020-08-04 09:13
Disable cache header when testing.

**Comment by tabeckers** [comment] 2020-08-05 09:34
![image](https://user-images.githubusercontent.com/26200358/89395520-bafe5c00-d70d-11ea-9a91-10be9565c2c0.png)

All addresses in the Marconistraat exist in our FunderMaps production database. A join between address, residential object and premise was used to retrieve this information:

```
SELECT * FROM geospatial.address AS a 
JOIN geospatial.residential_object AS ro ON ro.designation = a.id 
JOIN geospatial.premise AS p ON p.residential_object = ro.id
WHERE a.street = 'marconistraat'
AND a.city = 'schiedam'
```

**Comment by yorickdewid** [comment] 2020-08-05 09:45
The issue is resolved in database, which is what this issue covers. Anything else is not related to the database but to the application or cache

**Closed** 2020-08-05 09:49 UTC
Labels: Database, enhancement
